GET http://localhost:3000/info

###
GET http://localhost:3000/api/persons

###
GET http://localhost:3000/api/persons/3

###
POST http://localhost:3000/api/persons
Content-Type: application/json

{
    "name": "abcd",
    "number": "123"
}

###
PUT http://localhost:3000/api/persons/3
Content-Type: application/json

{
    "name": "abcde",
    "number": "123"
}

###
DELETE  http://localhost:3000/api/persons/3
